### ISSUE TITLE
Old TalkBank links

### ISSUE THREAD

**Issue by macw** [clarin-eric/clarin-curation-module#81] opened 2021-04-12 18:01 UTC
Dear Curation,
    The curation page for TalkBank lists 21 broken links.  However, none of these are in the most recent harvesting of our CMDI data that we uploaded.  Instead it appears that old records are not being removed.  When we upload a new inventory of records, it would be best to remove old ones.

--Brian MacWhinney  macw@cmu.edu

**Comment by wowasa** [comment] 2021-04-13 09:05
Dear Brian, 

due to the transfer of the curation project from acdh to clarin servers we face some irregularities in the link checking process and its results - usually reports are generated two times a week and only the results of the links of the latest run are displayed. 
I'm working on the issue and all database irregularities should be fixed by the end of this week. 

best regards
wolfgang

**Comment by macw** [comment] 2021-04-13 13:42
Many thanks.  This is a great resource and it is also good to know that you are keeping it up to date.

— Brian MacWhinney
Teresa Heinz Professor of Cognitive Psychology, 
Language Technologies and Modern Languages, CMU

**Comment by wowasa** [comment] 2021-04-27 09:19
just a little feedback: we figured out that our mariadb dms is by default not case sensitive, which is the cause of the issue. For the moment we're going to do a work around this week by deleting the 21 old links which return a 404-error, reloading the new links to be re-checked then. 
In the next major release 5.1.0 we will assure the case sensitivity of all string lockups, since we're going to change the database design anyway.

**Comment by macw** [comment] 2021-04-27 14:36
Wolfgang,

Thanks for fixing this.  No rush.

— Brian MacWhinney
Teresa Heinz Professor of Cognitive Psychology, 
Language Technologies and Modern Languages, CMU

**Comment by wowasa** [comment] 2021-05-04 08:47
correction on production data is done. I'm closing the issue

**Closed by wowasa** 2021-05-04 08:47 UTC
