### ISSUE TITLE
validation is not namespace aware

### ISSUE THREAD

**Issue by menzowindhouwer** [clarin-eric/clarin-curation-module#6] opened 2016-05-02 08:42 UTC
The current validation is not namespace aware, this allows invalid CMD records to pass through unnoticed. Take for example:

https://vlo.clarin.eu/data/clarin/results/cmdi/Huygens_Metadata_Repository/oai_oaipmh_huygens_knaw_nl_womenwriters_ffffdb1c_e0b2_4ceb_8720_e13b2498b5bb.xml

The cmdi:Components child elements are all member of the default namespace with URI http://www.openarchives.org/OAI/2.0/. This is not possible in a CMDI records, so this record should be considered invalid.

**Comment by wowasa** [comment] 2019-01-11 18:49
the recently published curation 2.0 is namespace aware

**Comment by twagoo** [comment] 2019-02-27 08:44
>the recently published curation 2.0 is namespace aware
Looks fixed indeed (though Huygens collections are no longer available). Maybe close this?

**Comment by wowasa** [comment] 2021-05-04 09:00
this was already fixed in 2019. Although "fixed" is probably not the right expression since I assume the non namespace awareness was one an intended behaviour

**Closed by wowasa** 2021-05-04 09:00 UTC
